---
title: "Covid 19 Final Project"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
#import all the libs
library(flexdashboard)
library(tidyverse)
library(highcharter)
library(gt)
library(htmltools)
library(viridis)
library(ggplot2)
library(dplyr)

```

```{r, getdata}
#import data

url_in <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/"

file_names <-
c("time_series_covid19_confirmed_global.csv",
"time_series_covid19_deaths_global.csv",
"time_series_covid19_confirmed_US.csv",
"time_series_covid19_deaths_US.csv")

urls <- str_c(url_in,file_names)
global_cases <- read_csv(urls[1])
global_deaths <- read_csv(urls[2])
US_cases <- read_csv(urls[3])
US_deaths <- read_csv(urls[4])

uid_lookup_url <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/UID_ISO_FIPS_LookUp_Table.csv"



```


Steven Sharp 2023 work in R
===============================================================================


Column {tabset .tabset-fade data-width=650}
-----------------------------------------------------------------------

### New cases & Deaths US 

```{r}

#tidy the data up
global_cases <-global_cases %>%
pivot_longer(cols = -c(`Province/State`,`Country/Region`,Lat,Long),
names_to ="date",
values_to = "cases") %>%
  select(-c(Lat,Long))

global_deaths <- global_deaths %>%
pivot_longer(cols = -c(`Province/State`,`Country/Region`,Lat,Long),
names_to ="date",
values_to = "deaths") %>%
  select(-c(Lat,Long))
  
global <- global_cases %>%
full_join(global_deaths) %>%
rename(Country_Region = `Country/Region`,
Province_State = `Province/State`) %>%
mutate(date = mdy(date))

global <- global %>% filter(cases >0)


 
 
## US cases clean up
US_cases <- US_cases %>%
 pivot_longer(cols = -(UID:Combined_Key),
  names_to ="date",
  values_to = "cases") %>%
  select(Admin2:cases) %>%
  mutate(date = mdy(date)) %>%
  select(-c(Lat,Long_))
 
## US deaths

US_deaths <- US_deaths %>%
 pivot_longer(cols = -(UID:Population),
  names_to ="date",
  values_to = "deaths") %>%
  select(Admin2:deaths) %>%
  mutate(date = mdy(date)) %>%
  select(-c(Lat,Long_))
  
## Join data
US <- US_cases %>% full_join(US_deaths)


## combine data
global <-global %>%
  unite("Combined_Key",
  c(Province_State, Country_Region),
  sep = ", ",
  na.rm =TRUE,
  remove=FALSE)
  
## grab population of coutries
uid <- read_csv(uid_lookup_url) %>%
  select(-c(Lat, Long_,Combined_Key, code3, iso2, iso3, Admin2))
  
## join the data to add population

global <- global %>%
left_join(uid, by = c("Province_State", "Country_Region"),y) %>%
  select(-c(UID, FIPS)) %>%
  select(Province_State, Country_Region, date, cases, deaths, Population,
  Combined_Key)

##vis
US_by_state <-US %>%
group_by(Province_State, Country_Region, date) %>%
summarize(cases = sum(cases), deaths = sum(deaths),
  Population = sum(Population)) %>%
  mutate(deaths_per_mill = (deaths*1000000)/Population) %>%
  select(Province_State, Country_Region, date,
  cases, deaths, deaths_per_mill, Population) %>%
  ungroup()

US_totals <- US_by_state %>%
group_by(Country_Region, date) %>%
summarize(cases = sum(cases), deaths = sum(deaths),
  Population = sum(Population)) %>%
  mutate(deaths_per_mill = (deaths*1000000)/Population) %>%
  select(Country_Region, date,
    cases, deaths, deaths_per_mill, Population) %>%
  ungroup()

US_totals %>%
  filter(cases > 0) %>%
  ggplot(aes(x = date, y = cases)) +
  geom_line(color = "black") +
  geom_point(color = "black") +
  geom_line(aes(y = deaths), color = "red") +
  geom_point(aes(y = deaths), color = "red") +
  scale_y_log10() +
  theme(legend.position = "bottom", axis.text.x = element_text(angle = 90)) +
  labs(title = "COVID 19 in the US", y = NULL)


```

### New cases & Deaths Florida

```{r}
State <- "Florida"
US_by_state %>%
filter(Province_State == State) %>%
filter(cases > 0) %>%
ggplot(aes(x=date, y= cases))+
geom_line(aes(color = "cases"))+
geom_point(aes(color = "cases"))+
geom_line(aes(y=deaths, color ="deaths"))+
geom_point(aes(y= deaths, color="deaths"))+
scale_y_log10()+
theme(legend.position="bottom", axis.text.x = element_text(angle=90))+
labs(title = str_c("Covid19 in" ,State), y=NULL)

```


Column {data-width=350}
-----------------------------------------------------------------------

### Top 5 states Death rate 

```{r}

# analyse
US_state_totals <-US_by_state %>%
group_by(Province_State) %>%
summarize(deaths = max(deaths), cases = max(cases),
  population =max(Population),
  cases_per_thou = 1000*cases/population,
  deaths_per_thou = 1000* deaths/population) %>%
  filter(cases > 0, population >0)


# get top 5 states in US by death rate;
top5 <- US_state_totals %>%
slice_max(deaths_per_thou, n=5) %>%
select(deaths_per_thou, cases_per_thou, everything())

library(ggplot2)

# Create a bar plot of deaths_per_thou for the top 5 states
bar_plot <- ggplot(top5, aes(x = reorder(Province_State, -deaths_per_thou), y = deaths_per_thou)) +
  geom_bar(stat = "identity", fill = "skyblue", width = 0.5) +
  labs(title = "Top 5 States by Death Rate",
       x = "State",
       y = "Deaths per Thousand") +
  theme(axis.text.x = element_text(angle = 0, hjust = 1)) +
  coord_flip()

# Calculate the average death rate
average_death_rate <- mean(top5$deaths_per_thou)

# Add an average line to the plot
bar_plot_with_average <- bar_plot +
  geom_hline(yintercept = average_death_rate, color = "red", linetype = "dashed") +
  annotate("text", x = 1, y = average_death_rate, label = "Average",
           hjust = -0.5, vjust = 0.5, color = "red", size = 3)

# Print the bar plot with the average line
print(bar_plot_with_average)


```

### Modeling/Prediction

```{r}


# Take the logarithm of the variables
US_state_totals$log_cases_per_thou <- log(US_state_totals$cases_per_thou)
US_state_totals$log_deaths_per_thou <- log(US_state_totals$deaths_per_thou)

# Fit a logarithmic model
mod <- lm(log_deaths_per_thou ~ log_cases_per_thou, data = US_state_totals)
summary(mod)

# Add predicted values to the data frame
US_tot_w_pred <- US_state_totals %>% mutate(pred = exp(predict(mod)))

# Plot the data points and predicted values
US_tot_w_pred %>% ggplot() +
  geom_point(aes(x = log_cases_per_thou, y = log_deaths_per_thou), color = "blue") +
  geom_line(aes(x = log_cases_per_thou, y = log(pred)), color = "red") +
  labs(title = "Logarithmic Fit of Deaths per Thousand vs. Cases per Thousand",
       x = "Log Cases per Thousand",
       y = "Log Deaths per Thousand") +
  theme_minimal()

```

